-- Create the leads table (if not exists)
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  phone text,
  project_type text,
  location text,
  start_date text,
  description text
);

-- Enable Row Level Security
alter table public.leads enable row level security;

-- Create policy to allow anonymous inserts
create policy "Enable insert for everyone" 
on public.leads 
for insert 
with check (true);

-- Optional: Create policy to allow reading leads (Authenticated users only?)
-- create policy "Enable read access for service role only" on public.leads for select using (true);
